kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    extended: true
    hugo_version: "0.104.3"
    config: config.yaml

- name: publish
  image: plugins/netlify
  settings:
    path: ./public
    prod: true
    site:
      from_secret: netlify_site_id
    token:
      from_secret: netlify_token
  when:
    event:
    - push
    branch:
    - master

trigger:
  event:
  - push
  - pull_request
